### ISSUE TITLE
(StreamerMode) More Hiddens [list]

### ISSUE THREAD

**Issue by VioletStorm** [DiamondMiner88/aliucord-plugins#1]
After using the plug-in for a day, there are several things I'd like to request added to the hiding options, that I've noticed might be desirable to remove under certain circumstances.

1: Account Names and Mutuals within Connections (both on user profiles and in settings, with a warning pop-up if tapped)

2: Server Images in Sidebar (perhaps replace with the first two letters of the server name)

3: Friend Names/Icons (again replacing the image with the first two letters of their username and censoring all but those letters in the list would probably work best)

4: Timestamps on Messages (if global region is private information)

5: User AKAs (the names they use in other servers, which can sometimes contain gametags ect)

6: The [+] Media Selector Button (I think just a warning pop-up would be better than removal though)

**Comment by DiamondMiner88** [comment]
> 6: The [+] Media Selector Button (I think just a warning pop-up would be better than removal though)

why

**Comment by rushiiMachine** [comment]
> 2: Server Images in Sidebar (perhaps replace with the first two letters of the server name)
> 3: Friend ~~Names~~/Icons (again replacing the image with the first two letters of their username and censoring all but those letters in the list would probably work best)
> 4: Timestamps on Messages (if global region is private information)
> 6: The [+] Media Selector Button (I think just a warning pop-up would be better than removal though)

These should all be a separate plugin(s)

**Comment by rushiiMachine** [comment]
Finished the other ones, also made no timestamps <https://github.com/DiamondMiner88/aliucord-plugins#notimestamps>
