### ISSUE TITLE
(FriendsExporter) Remove MarkDown-Formatting + CSV export

### ISSUE THREAD

**Issue by noahstreller** [DiamondMiner88/aliucord-plugins#11]
When someone has an underscore or a star in the name, they will act as MD-Formatting options. This can be avoided by using a "\\" in front of the formatting symbols.

I would also love to see an option to export as CSV, but it works fine already and I appreciate your work.

**Comment by noahstreller** [comment]
I meant the backslash symbol to skip the MD-formatting: \\

**Comment by rushiiMachine** [comment]
fixed
just do a of regex to make it into csv not hard
