### ISSUE TITLE
1click delete

### ISSUE THREAD

**Issue by megacool2325** [DiamondMiner88/aliucord-plugins#12]
When you delete a message with confirmations it automatically gets rid of the menu that shows the delete,react,share etc but with 1click delete it stays up and I find this rather annoying having to manually scroll down to get rid of main menu even if this was a setting that we could enable for this, that would be totally awesome!

**Comment by rushiiMachine** [comment]
oops

**Comment by rushiiMachine** [comment]
fixed, building now
