### ISSUE TITLE
AlternateReport's message link missing the server's ID

### ISSUE THREAD

**Issue by NightWorshiper** [DiamondMiner88/aliucord-plugins#16]
Hey, whenever I try reporting someone's message and the Trust & Safety form opens, the message link seems to never work. I got used to it and I always came back and copied the message link with another plugin and proceeded without any issues, but I've got tired lol. 

The message link that goes to my clipboard whenever I open the form does not contain the ID of the said server (if the message is from a server, obviously). The image below describes it perfectly.

![IMG_20220924_224030](https://user-images.githubusercontent.com/88115338/192118449-4decc4ea-4aa2-41f2-b1b2-f2527fb87a59.jpg)

NOTE¹: The first link is the one that goes to my clipboard when I'm reporting someone while the second one is the message link, which was manually copied.

NOTE²: They're from the same message

**Comment by rushiiMachine** [comment]
huh i guess they changed it
