### ISSUE TITLE
(StreamerMode) Quick Toggle

### ISSUE THREAD

**Issue by VioletStorm** [DiamondMiner88/aliucord-plugins#2]
A toggle from within the Set Status page which can enable/disable StreamerMode entirely would be extremely useful!

**Comment by rushiiMachine** [comment]
Useless, it'll require a restart anyways

**Comment by VioletStorm** [comment]
> Useless, it'll require a restart anyways

Disagree, when you enable/disable it the app can then restart itself automatically.

Currently you have to go into settings, plugins, searching for StreamerMode, toggling on/off, then finally manually restart.

Please explain how that is better than holding your profile and tapping one button?

**Comment by rushiiMachine** [comment]
> Set Status

One of the most random places for a toggle, find something better imo

**Comment by VioletStorm** [comment]
> 

My thinking with that location is it's quickly accessable, and since Streamer Mode is an actual status on desktop discord (albeit one which iirc is automatically activated), it made sense as that location.

**Comment by rushiiMachine** [comment]
I'm thinking of making a separate plugin to quick toggle with maybe a command `/toggle plugin:<autocompleted list>`

**Comment by VioletStorm** [comment]
> I'm thinking of making a separate plugin to quick toggle with maybe a command `/toggle plugin:<autocompleted list>`

Now that would be *very* useful
