### ISSUE TITLE
Add an option to hide replies to messages from blocked users

### ISSUE THREAD

**Issue by abhisheksahdev** [DiamondMiner88/aliucord-plugins#5]
For example:

say A (blocked user) messages in a channel and someone else (not blocked) replies to it, hide the message which was sent in reply to the blocked user's text.

Please tell me know if you do not understand.

**Comment by rushiiMachine** [comment]
This should be added to HideBlockedMessages instead

https://github.com/lexisother/AliucordPlugins/issues
