### ISSUE TITLE
(BetterTm) tm isn't visibly modified

### ISSUE THREAD

**Issue by solonovamax** [DiamondMiner88/aliucord-plugins#9]
The :tm: emoji isn't modified at all, and remains the same.

See: https://imgur.com/a/Mc6cn5Q (mobile; can't upload images to github rn)

Neither "original" nor the replacement work.

For testing purposes, I disabled all other plugins & restarted several times. Issue still occurs.

**Comment by rushiiMachine** [comment]
~~Try with the copyright & trademark emoji please as well.~~
EDIT: I've reproduced the issue

Also this plugin won't work with light mode anyways.
It would be literally invisible since the replacement is 100% white

**Comment by solonovamax** [comment]
> Also this plugin won't work with light mode anyways.
> It would be literally invisible since the replacement is 100% white

Yes, I was just using light mode to show that the icons are unchanged.

**Comment by lilyremigia** [comment]
I don't know if it's related to this issue or not, but for me, it replaces 7️⃣`:seven:` and 8️⃣`:eight:`.

[Screenshot](https://cdn.discordapp.com/attachments/568178625766096916/958641340210634792/Screenshot_20220330-101813.jpg)

**Comment by rushiiMachine** [comment]
about what i expected, the emoji ids have been offset
ill fix when i have time

**Comment by rushiiMachine** [comment]
fixed
